### ISSUE TITLE
Port configuration without Amazon EC2

### ISSUE THREAD

**Issue by MyleneSimon** [pegasus-isi/pegasus-docker-deploy#1]
Hi,

I hope this is not too out of topic. I tried to adapt the pegasus-docker-deploy script in order to create the swarm cluster on my machine instead of the Amazon Cloud for testing.
To do so, I removed the parts specific to the EC2 configuration and used the virtualbox driver for the docker machines instead of the amazonec2 one.

Now, if I log into the pegasus submit container, and I run the `condor-status`command, I don't see the worker nodes. I thought that it was because the ports were not properly configured, so I tried to forward the ports that were described in the original script from the docker machines using the VirtualBox interface, but I still have the same issue.

Is there anything else that I should in order for the submit container to see the workers?

Thanks.

**Comment by rafaelfsilva** [comment]
Hi @MyleneSimon,

Sorry for the late response. I will be updating the script to support both Amazon and VirtualBox. It should be available by next week.

Rafael

**Comment by rafaelfsilva** [comment]
Hi @MyleneSimon,

I have updated the script to support VirtualBox. Once you have cloned the repository, you only need to run the following command:

```
./pegasus-docker-deploy
```

This will deploy Pegasus with 1 worker node. To ask for more worker nodes pass `-n 5` as an argument to the deployment command:

```
./pegasus-docker-deploy -n 5
```

I still need to improve the script with error checks. Once this will be available, I will close your issue.
